import type { NextPage } from "next";
import { Fragment } from "react";
import PreviewCode from "../../../components/PreviewCode";
import { structure } from "./data/fonts";

const AzeroothFeatureFonts: NextPage = () => {
  return (
    <Fragment>
      <h1>Fonts</h1>
      Azerooth permet facilement d&#39;appliquer d&#39;autre <code>
        fonts
      </code>{" "}
      que celle utilisé par default par <b>Material Design</b>. Grâce au système
      de gestion de theme vous pouvez personnaliser pour tout ou une partie de
      votre application. Elle applique les bases de la typography de Material
      Design
      <h3>Configuration</h3>
      <PreviewCode code={structure}></PreviewCode>
      Cette configuration vous permet ensuite d&#39;utiliser des classes avec
      une gestion des breakpoints afin de personnaliser le plus possible votre
      projet.
      <b> D&#39;autre développement sont en cours pour cette fonctionnalité</b>
      Vous pouvez donc utiliser ces classes :
      <ul>
        <li>
          <b>text-h1</b>
        </li>
        <li>
          <b>text-h2</b>
        </li>
        <li>
          <b>text-h3</b>
        </li>
        <li>
          <b>text-h4</b>
        </li>
        <li>
          <b>text-h5</b>
        </li>
        <li>
          <b>text-h6</b>
        </li>
        <li>
          <b>text-subtitle-1</b>
        </li>
        <li>
          <b>text-subtitle-2</b>
        </li>
        <li>
          <b>text-body-1</b>
        </li>
        <li>
          <b>text-body-2</b>
        </li>
        <li>
          <b>text-button</b>
        </li>
        <li>
          <b>text-caption</b>
        </li>
        <li>
          <b>text-overline</b>
        </li>
      </ul>
      En utilisant les breakpoints les classes seront écrite de cette façon:{" "}
      <code>{`text-{size}-{mode}`}</code>
      <ul>
        <li>
          <b>text-sm-h1</b>
        </li>
        <li>
          <b>text-md-h1</b>
        </li>
        <li>
          <b>text-lg-h1</b>
        </li>
        <li>
          <b>text-xl-h1</b>
        </li>
        <li>
          <b>text-sm-h2</b>
        </li>
        <li>
          <b>text-md-h2</b>
        </li>
        <li>
          <b>text-lg-h2</b>
        </li>
        <li>
          <b>text-xl-h2</b>
        </li>
        <li>
          <b>text-sm-h3</b>
        </li>
        <li>
          <b>text-md-h3</b>
        </li>
        <li>
          <b>text-lg-h3</b>
        </li>
        <li>
          <b>text-xl-h3</b>
        </li>
        <li>
          <b>text-sm-h4</b>
        </li>
        <li>
          <b>text-md-h4</b>
        </li>
        <li>
          <b>text-lg-h4</b>
        </li>
        <li>
          <b>text-xl-h4</b>
        </li>
        <li>
          <b>text-sm-h5</b>
        </li>
        <li>
          <b>text-md-h5</b>
        </li>
        <li>
          <b>text-lg-h5</b>
        </li>
        <li>
          <b>text-xl-h5</b>
        </li>
        <li>
          <b>text-sm-h6</b>
        </li>
        <li>
          <b>text-md-h6</b>
        </li>
        <li>
          <b>text-lg-h6</b>
        </li>
        <li>
          <b>text-xl-h6</b>
        </li>
        <li>
          <b>text-sm-subtitle-1</b>
        </li>
        <li>
          <b>text-md-subtitle-1</b>
        </li>
        <li>
          <b>text-lg-subtitle-1</b>
        </li>
        <li>
          <b>text-xl-subtitle-1</b>
        </li>
        <li>
          <b>text-sm-subtitle-2</b>
        </li>
        <li>
          <b>text-md-subtitle-2</b>
        </li>
        <li>
          <b>text-lg-subtitle-2</b>
        </li>
        <li>
          <b>text-xl-subtitle-2</b>
        </li>
        <li>
          <b>text-sm-body-1</b>
        </li>
        <li>
          <b>text-md-body-1</b>
        </li>
        <li>
          <b>text-lg-body-1</b>
        </li>
        <li>
          <b>text-xl-body-1</b>
        </li>
        <li>
          <b>text-sm-body-2</b>
        </li>
        <li>
          <b>text-md-body-2</b>
        </li>
        <li>
          <b>text-lg-body-2</b>
        </li>
        <li>
          <b>text-xl-body-2</b>
        </li>
        <li>
          <b>text-sm-button</b>
        </li>
        <li>
          <b>text-md-button</b>
        </li>
        <li>
          <b>text-lg-button</b>
        </li>
        <li>
          <b>text-xl-button</b>
        </li>
        <li>
          <b>text-sm-caption</b>
        </li>
        <li>
          <b>text-md-caption</b>
        </li>
        <li>
          <b>text-lg-caption</b>
        </li>
        <li>
          <b>text-xl-caption</b>
        </li>
        <li>
          <b>text-sm-overline</b>
        </li>
        <li>
          <b>text-md-overline</b>
        </li>
        <li>
          <b>text-lg-overline</b>
        </li>
        <li>
          <b>text-xl-overline</b>
        </li>
      </ul>
    </Fragment>
  );
};

export default AzeroothFeatureFonts;
